spring:
  application:
    name: money-app
  datasource:
    driver-class-name: org.h2.Driver
    username: app
    password: root
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create